# Generated by Django 2.2.19 on 2022-09-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220906_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='group_url_name',
        ),
    ]
