# Generated by Django 2.2.19 on 2022-09-07 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220906_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_url_name',
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
